# Generated by Django 5.2.5 on 2025-08-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='dark', max_length=8)),
                ('font_px', models.PositiveIntegerField(default=16)),
                ('lock_pin', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('national_id', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='نشط', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='app_core_cu_name_86a7e2_idx'), models.Index(fields=['phone'], name='app_core_cu_phone_6ebd9f_idx'), models.Index(fields=['national_id'], name='app_core_cu_nationa_6e4f9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('maintenance_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_type', models.CharField(choices=[('installment', 'installment'), ('cash', 'cash')], default='installment', max_length=16)),
                ('schedule_type', models.CharField(blank=True, default='شهري', max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('extra_annual', models.IntegerField(default=0)),
                ('annual_payment_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start', models.DateField()),
                ('broker_name', models.CharField(blank=True, default='', max_length=255)),
                ('broker_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('broker_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='app_core.customer')),
                ('commission_safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_contracts', to='app_core.safe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrokerDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('due', 'due'), ('paid', 'paid')], default='due', max_length=8)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.broker')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_dues', to='app_core.contract')),
                ('paid_from_safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.safe')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('from_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='app_core.safe')),
                ('to_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='app_core.safe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('floor', models.CharField(blank=True, default='', max_length=64)),
                ('building', models.CharField(blank=True, default='', max_length=64)),
                ('unit_type', models.CharField(blank=True, default='سكني', max_length=64)),
                ('area', models.CharField(blank=True, default='', max_length=64)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('متاحة', 'متاحة'), ('محجوزة', 'محجوزة'), ('مباعة', 'مباعة'), ('مرتجعة', 'مرتجعة')], default='متاحة', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='app_core_un_code_95515d_idx'), models.Index(fields=['status'], name='app_core_un_status_40301d_idx'), models.Index(fields=['building', 'floor', 'name'], name='app_core_un_buildin_25309c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('غير مدفوع', 'غير مدفوع'), ('مدفوع', 'مدفوع')], default='غير مدفوع', max_length=16)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('owed_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_to_collect', to='app_core.partner')),
                ('paying_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_to_pay', to='app_core.partner')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_debts', to='app_core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('غير مدفوع', 'غير مدفوع'), ('مدفوع جزئياً', 'مدفوع جزئياً'), ('مدفوع', 'مدفوع')], default='غير مدفوع', max_length=16)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='app_core.unit')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='app_core.unit'),
        ),
        migrations.CreateModel(
            name='UnitPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partners', to='app_core.partner')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partners', to='app_core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('receipt', 'receipt'), ('payment', 'payment')], max_length=8)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('payer', models.CharField(blank=True, default='', max_length=255)),
                ('beneficiary', models.CharField(blank=True, default='', max_length=255)),
                ('raw_linked_ref', models.CharField(blank=True, default='', max_length=255)),
                ('broker_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app_core.brokerdue')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app_core.contract')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app_core.installment')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='app_core.safe')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='app_core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_core.partnergroup')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.partner')),
            ],
            options={
                'unique_together': {('group', 'partner')},
            },
        ),
        migrations.AddIndex(
            model_name='brokerdue',
            index=models.Index(fields=['status', 'due_date'], name='app_core_br_status_2824d1_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdebt',
            index=models.Index(fields=['status', 'due_date'], name='app_core_pa_status_e23dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['unit', 'due_date'], name='app_core_in_unit_id_3748dc_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status'], name='app_core_in_status_f22698_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitpartner',
            unique_together={('unit', 'partner')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date'], name='app_core_vo_date_dd3b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['type'], name='app_core_vo_type_1b29fb_idx'),
        ),
    ]
